# Generated by Django 3.0.1 on 2020-01-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
            ],
        ),
    ]
