# Generated by Django 3.0.1 on 2020-01-09 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 11, 11, 2, 92435), verbose_name='taken_on'),
        ),
    ]
