# Generated by Django 3.0.1 on 2020-01-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_books_taken_taken_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(verbose_name='taken_on'),
        ),
    ]
