# Generated by Django 3.0.1 on 2020-01-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20200109_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
            ],
        ),
    ]
