# Generated by Django 3.0.1 on 2020-01-09 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_books_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 14, 3, 7, 661608), verbose_name='taken_on'),
        ),
    ]
